apiVersion: apps/v1
kind: Deployment
metadata:
  name: breakdown-assistant
  namespace: default
spec:
  selector:
    matchLabels:
      app: breakdown-assistant
  replicas: 1
  template:
    metadata:
      name: breakdown-assistant
      labels:
        app: breakdown-assistant
    spec:
      containers:
      - name: breakdown-assistant
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: shagunchauhan/on-road-vehicle-breakdown-assistance-system:sprint2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: breakdown-assistant
  name: breakdown-assistant
spec:
  ports:
    - name: breakdown-assistant
      port: 8080
      protocol: TCP
  selector:
    app: breakdown-assistant
  type: NodePort